import 'report.dart';
import 'sms_message.dart';

// ─── Mock incident reports (matching the website's mock data) ──────────────
final List<IncidentReport> mockReports = [
  IncidentReport(
    id: '1722340800000',
    hazardType: HazardType.landslide,
    severity: SeverityLevel.severe,
    title: 'Km 42 Mountain Mudslide Blockade',
    highway: 'NH-415',
    chainage: 'Km 42.4',
    passability: PassabilityStatus.blocked,
    clearanceEta: '3–6 Hours',
    gpsData: GpsData(
      latitude: 27.70154,
      longitude: 95.05122,
      altitude: 818.0,
      accuracy: 2.4,
      capturedAt: DateTime.now().subtract(const Duration(minutes: 25)),
    ),
    hasVoiceMemo: true,
    syncStatus: SyncStatus.synced,
    createdAt: DateTime.now().subtract(const Duration(minutes: 25)),
    reportedBy: 'Field Officer Priya Das',
  ),
  IncidentReport(
    id: '1722340900000',
    hazardType: HazardType.bridgeFracture,
    severity: SeverityLevel.moderate,
    title: 'Expansion Joint Fracture — SH-15 Bridge',
    highway: 'SH-15',
    chainage: 'Km 18.2',
    passability: PassabilityStatus.singleLane,
    clearanceEta: '12–24 Hours',
    gpsData: GpsData(
      latitude: 26.90004,
      longitude: 93.90017,
      altitude: 145.0,
      accuracy: 4.1,
      capturedAt: DateTime.now().subtract(const Duration(minutes: 10)),
    ),
    hasVoiceMemo: false,
    syncStatus: SyncStatus.pending,
    createdAt: DateTime.now().subtract(const Duration(minutes: 10)),
    reportedBy: 'Field Officer Priya Das',
  ),
  IncidentReport(
    id: '1722340700000',
    hazardType: HazardType.flashFlood,
    severity: SeverityLevel.catastrophic,
    title: 'Flash Flood — NH-27 Dibrugarh Bypass',
    highway: 'NH-27',
    chainage: 'Km 88.0',
    passability: PassabilityStatus.blocked,
    clearanceEta: '24–48 Hours',
    gpsData: GpsData(
      latitude: 27.48220,
      longitude: 94.91340,
      altitude: 98.0,
      accuracy: 5.2,
      capturedAt: DateTime.now().subtract(const Duration(hours: 2)),
    ),
    hasVoiceMemo: true,
    syncStatus: SyncStatus.synced,
    createdAt: DateTime.now().subtract(const Duration(hours: 2)),
    reportedBy: 'Field Officer Rajan Bora',
  ),
  IncidentReport(
    id: '1722340600000',
    hazardType: HazardType.treeDebris,
    severity: SeverityLevel.minor,
    title: 'Fallen Trees Partially Blocking BRO-104',
    highway: 'BRO-104',
    chainage: 'Km 12.8',
    passability: PassabilityStatus.caution,
    clearanceEta: '1–3 Hours',
    gpsData: GpsData(
      latitude: 28.14560,
      longitude: 94.32780,
      altitude: 1240.0,
      accuracy: 3.6,
      capturedAt: DateTime.now().subtract(const Duration(hours: 4)),
    ),
    hasVoiceMemo: false,
    syncStatus: SyncStatus.synced,
    createdAt: DateTime.now().subtract(const Duration(hours: 4)),
    reportedBy: 'Field Officer Priya Das',
  ),
  IncidentReport(
    id: '1722340500000',
    hazardType: HazardType.heavyStorm,
    severity: SeverityLevel.moderate,
    title: 'Severe Storm Warning — NH-13 Anjaw Sector',
    highway: 'NH-13',
    chainage: 'Km 204.0',
    passability: PassabilityStatus.caution,
    clearanceEta: '6–12 Hours',
    gpsData: GpsData(
      latitude: 28.06810,
      longitude: 96.08230,
      altitude: 1520.0,
      accuracy: 6.0,
      capturedAt: DateTime.now().subtract(const Duration(hours: 6)),
    ),
    hasVoiceMemo: false,
    syncStatus: SyncStatus.pending,
    createdAt: DateTime.now().subtract(const Duration(hours: 6)),
    reportedBy: 'Field Officer Vikram Singh',
  ),
];

// ─── Mock SMS messages (matching the website's driver feed) ───────────────
List<SmsMessage> buildMockMessages() => [
  SmsMessage(
    id: 'sms-1',
    sender: 'NER-HQ-DISPATCH',
    text: 'CRITICAL REROUTE: NH-415 blocked at Km 42 (Landslide). Divert to SH-15 Safe Corridor. New ETA: 5h 45m. Confirm receipt.',
    timestamp: DateTime.now().subtract(const Duration(minutes: 12)),
    priority: MessagePriority.urgent,
  ),
  SmsMessage(
    id: 'sms-2',
    sender: 'NER-HQ-DISPATCH',
    text: 'WEATHER ADVISORY: Heavy rainfall 84 mm/hr in East Siang sector. Keep convoy speed below 45 km/h on mountain sections.',
    timestamp: DateTime.now().subtract(const Duration(minutes: 45)),
    priority: MessagePriority.warning,
  ),
  SmsMessage(
    id: 'sms-3',
    sender: 'NER-HQ-DISPATCH',
    text: 'DISPATCH ORDER: Convoy AR-01-GH-2345 cleared for departure. Medical Supplies priority payload. Gate #04 officer notified.',
    timestamp: DateTime.now().subtract(const Duration(hours: 2)),
    priority: MessagePriority.normal,
  ),
  SmsMessage(
    id: 'sms-4',
    sender: 'NER-HQ-DISPATCH',
    text: 'CHECKPOINT UPDATE: Pasighat Gate #04 operational. Field Officer NER-FO-8841 on duty. Show QR transit pass on arrival.',
    timestamp: DateTime.now().subtract(const Duration(hours: 3, minutes: 15)),
    priority: MessagePriority.normal,
    acknowledged: true,
  ),
];
